Am facut Domain classes si am inceput user_repository
caramandvd/Bank-Backend pull request #1
Opened 2023-02-21 11:52 UTC by caramandvd

Acum lucrez la functia "_add user_" to db.

2023-02-23 20:10 UTC, EcclesiaITAcademy requested changes
Well done! Left some suggestions and some nitpicks. Great job overall

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Utils/utils.py
> +
Nitpick: You can remove this extra spaces

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Utils/utils.py
> +# if __name__ == '__main__':
You don't need to comment this out. It will only run when you run utils.py directly.

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Utils/utils.py
> +#     Base.metadata.create_all(engine)
Since in the utils you only create a connection and use it elsewhere you can just test to see if the connection works:

`
try:
    engine.connect()
    print("Success")
except SQLAlchemyError as err:
    print("Error", err.__cause__)  # this will give what kind of error
`

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/atm_locations.py
> +from sqlalchemy import Column, String, Integer, Date, Float, ForeignKey, Double
Try to import only the things we're using (Date, Float, ForeignKey, Double not used but imported)

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/currencies.py
> +from sqlalchemy import Column, String, Integer, Date, Float, ForeignKey, Double
Same here

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/exchange_rates.py
> +from sqlalchemy import Column, String, Integer, DateTime, Float, ForeignKey, Double
Same

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/exchange_rates.py
> +    def __repr__(self):
Nitpick: An extra line above functions looks better. 

Pro tip: If it's underlined you can press "Alt" + "Enter" for suggestions. In this case "Reformat file" works best 
Also PyCharm has a "Problems" tab in the lower left that will tell you all the errors and warnings in the file

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/exchange_rates.py
> +    from_currency = Column(String(3))
A foreign key relationship is needed here

Something like this should work:

```
from sqlalchemy.orm import relationship

class Currencies(Base):
    __tablename__ = "currencies"
    currency = Column(String(3), primary_key=True)
    from_currency = relationship("ExchangeRates", backref="currencies")
    to_currency = relationship("ExchangeRates", backref="currencies")


class ExchangeRates(Base):
    __tablename__ = "exchange_rates"
    id = Column(Integer, primary_key=True)
    from_currency = Column(String(3), ForeignKey('currencies.id'))
    to_currency = Column(String(3), ForeignKey('currencies.id'))
    date_time = Column(DateTime)
    rate = Column(Float(2))

```

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/messages.py
> +    user_id = Column(String(13), primary_key=True, foreign_key=ForeignKey('users.user_id', ondelete="CASCADE"))
Add Foreign Key for user_id

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/users_accounts.py
> +    user_id = Column(String(13), foreign_key=ForeignKey('users.user_id', ondelete="CASCADE"))
Foreign Key

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/users_cards.py
> +    user_id = Column(String(13), foreign_key=ForeignKey('users.user_id', ondelete="CASCADE"))
Foreign Key

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/users_credentials.py
> +    user_id = Column(String(13), primary_key=True, foreign_key=ForeignKey("users.user_id", ondelete="CASCADE"))
Foreign Key

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/users_deposits.py
> +    user_id = Column(String(13), primary_key=True, foreign_key=ForeignKey("users.user_id", ondelete="CASCADE"))
Foreign Key

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/users_deposits.py
> +    currency = Column(String(3), foreign_key=ForeignKey('currencies.currency', ondelete="CASCADE"))
Foreign Key

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/users_transaction.py
> +    user_id = Column(String(13), foreign_key=ForeignKey("users.user_id", ondelete="CASCADE"), autoincrement=True)
Foreign Key

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/users_transaction.py
> +    currency = Column(String(3), foreign_key=ForeignKey("currencies.currency", ondelete="CASCADE"))
Foreign Key

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Domain/users_accounts.py
> +    currency = Column(String(3))
Foreign Key

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Repository/currencies_repository.py
> +        engine = create_engine('mysql+pymysql://root@localhost:3306/bankdashboarddb')
We can import the engine from utils, no need to initiate a new one everytime

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Repository/users_accounts_repository.py
> +        engine = create_engine('mysql+pymysql://root@localhost:3306/bankdashboarddb')
Same here

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Repository/users_accounts_repository.py
> +        if amount:
What happens if the amount is None? How do we know if the update reached the DB or not?

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Repository/users_repository.py
> +        engine = create_engine('mysql+pymysql://root@localhost:3306/bankdashboarddb')
Same

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Repository/users_repository.py
> +            centuries = {
Nice! Cool approach!

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Repository/users_repository.py
> +        print(kwargs)
It's fine for now, but usualy it's better to not commit prints or debugging code to production

2023-02-23 20:10 UTC, EcclesiaITAcademy commented on Model/Repository/users_transaction_repository.py
> +        engine = create_engine('mysql+pymysql://root@localhost:3306/bankdashboarddb')
Same

2023-02-23 20:11 UTC, EcclesiaITAcademy commented
Also, let's write in English. Create a more realistic and professional experience 😄

2023-02-25 13:09 UTC, EcclesiaITAcademy commented
You can press on "Resolve conversation" where you did the changes so it's easier to follow

2023-02-26 19:49 UTC, EcclesiaITAcademy requested changes

2023-02-26 19:49 UTC, EcclesiaITAcademy commented on Model/Domain/exchange_rates.py
> +class Currencies(Base):
This goes in currencies.py

2023-02-26 19:49 UTC, EcclesiaITAcademy commented on Model/Repository/atm_locations_repository.py
> +        self.session = sessionmaker(create_engine('mysql+pymysql://root@localhost:3306/bankdashboarddb'))()
Use engine from utils here

2023-02-26 19:49 UTC, EcclesiaITAcademy commented on Model/Repository/messages_repository.py
> +        self.session = sessionmaker(create_engine('mysql+pymysql://root@localhost:3306/bankdashboarddb'))()
Use engine from utils

2023-02-26 19:49 UTC, EcclesiaITAcademy commented on Model/Repository/users_credentials_repository.py
> +        self.session = sessionmaker(create_engine('mysql+pymysql://root@localhost:3306/bankdashboarddb'))()
Use engine from utils

2023-02-26 19:49 UTC, EcclesiaITAcademy commented on Model/Repository/users_transaction_repository.py
> +        self.session = sessionmaker(create_engine('mysql+pymysql://root@localhost:3306/bankdashboarddb'))()
Use engine from utils

2023-02-26 19:52 UTC, EcclesiaITAcademy commented
You also need to add relationships for the foreign keys

2023-02-27 21:34 UTC, caramandvd commented on Model/Domain/exchange_rates.py
> +    from_currency = Column(String(3))
added in currencies.py the requested changes. @EcclesiaITAcademy, I need you to check if I did it right. Thank!

2023-02-28 09:07 UTC, EcclesiaITAcademy approved these changes
Still need to add the relationships but we can do it on another branch

2023-03-01 19:02 UTC, merged